name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: questappacr.azurecr.io/quest-app-image:latest

    - name: Azure Container Registry Logout
      run: docker logout questappacr.azurecr.io

    - name: Deploy to Azure
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az container create \
            --resource-group <resource-group-name> \
            --name quest-app \
            --image questappacr.azurecr.io/quest-app-image:latest
            --cpu 1 \
            --memory 1 \
            --registry-login-server questappacr.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }}

