name: Linux_Container_Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
        
      # Login to Azure
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build and push image
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}

      # Terraform steps
      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0  # Specify your Terraform version

      - name: 'Terraform Init'
        run: |
          cd terraform
          terraform init

      - name: 'Terraform Apply'
        run: |
          cd terraform
          terraform apply -auto-approve \
            -var "resource_group_name=${{ secrets.RESOURCE_GROUP }}" \
            -var "location=westus" \
            -var "container_group_name=aci-sampleapp" \
            -var "registry_login_server=${{ secrets.REGISTRY_LOGIN_SERVER }}" \
            -var "tag=${{ github.sha }}"
